server:
  port: 8082
spring:
  application:
    name: admin-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: health,info
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000
